### ISSUE TITLE
Counter must stop once it goes beyond imports group

### ISSUE THREAD

**Issue by marcusgaius** [ctf0/vscode-php-class-imports-folding#1]
In general, the extension works fine, but it breaks the UI if there are trait use imports. My suggestion would be adding control for certain keywords, namely `class`, but any way to indicate the line between imports and body of the code can work, I just think making a list of keywords that stop the loop would be the simplest approach.

**Comment by ctf0** [comment]
can u show me a code example ?

**Comment by marcusgaius** [comment]
![image](https://github.com/ctf0/vscode-php-class-imports-folding/assets/39379513/c8a968a7-57dd-4a2a-8aca-9b8e89a3e114)
![image](https://github.com/ctf0/vscode-php-class-imports-folding/assets/39379513/d75de6a2-7956-417c-82a2-da24c840e187)

This would be a simplest example. First picture shows an unfolded, the second one folded imports. You can see that the folding goes too far because it checks all the lines for a `use` statement, but it doesn't stop at the `class` statement.

**Comment by ctf0** [comment]
this is strange,  because we only check for the `use` call at the beginning of the line
https://github.com/ctf0/vscode-php-class-imports-folding/blob/2e1e83090aff7ad11fd64f81833a915bd30ac4de/src/extension.ts#L11

**Comment by marcusgaius** [comment]
Doesn't the `\s*` mean "any number of spaces"?

**Comment by ctf0** [comment]
yes but its not related to that, however i have found the issue, i will push the fix asap

**Comment by ctf0** [comment]
done
