### ISSUE TITLE
Import sometimes ignores the last case also removes folding for function class

### ISSUE THREAD

**Issue by SantanuDatta** [ctf0/vscode-php-class-imports-folding#2]
It seems like a hit-and-miss
![image](https://github.com/ctf0/vscode-php-class-imports-folding/assets/40891517/8f45ca53-3a08-4623-b0fd-ba2f2f042643)
but in another file, it folds nicely
![image](https://github.com/ctf0/vscode-php-class-imports-folding/assets/40891517/d0327a5f-8df0-42b9-83f7-f8146c1153c5)
but the main problem I am facing right now is it removes `class` & `function` statement folding completely 
this is without the use of this extension
![image](https://github.com/ctf0/vscode-php-class-imports-folding/assets/40891517/075aa6eb-56be-4730-bac5-b9bed5e4bf86)
this is with the use of this extension
![image](https://github.com/ctf0/vscode-php-class-imports-folding/assets/40891517/3878f132-5eb5-4e16-9e8c-9744bc877d2a)

**Comment by ctf0** [comment]
the thing is that vscode can only use one folding provider at a time, 
so without the ext this is the normal when u have the folding strategy by indentation, 
when u enable the ext it will only fold the use statements and nothing else, hence all the other folding marks will be gone. 

regarding the folding not taking into account the last use statement, i believe this is related to using another php pkg ex.`php intelephense` which sadly overrides the ext functionality

**Comment by SantanuDatta** [comment]
I see well that is sad, but thank you for the information
